# netlify.toml (en la raíz del proyecto)

[build]
  functions = "netlify/functions"
  publish = "dist" 

[dev]
  # El comando real para iniciar tu app de React
  command = "npm run dev"
  
  # El puerto que usa tu servidor React (Vite) en segundo plano
  targetPort = 5173 
  
  # El puerto que Netlify expone (ya configurado en 8888)
  port = 8888
  
  # Especificamos que estamos usando el framework Vite
  framework = "vite"